# Site settings
title: "徐晟桐的个人主页"
description: "徐晟桐的个人主页。"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "徐晟桐"
resume_title:                   "个人简介"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "fanmiao.cslt.thu@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "13581700448"
resume_contact_address:         "中国北京海淀区"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "

<p>高级研发总监；中国人民大学信息资源管理学院研究生行业导师。</p>

<p>澳洲国立大学XXX硕士、南开大学XX。</p>

<p>《Python机器学习及实践：从零开始通往Kaggle竞赛之路》作者。 </p>

<p>获美国、中国发明专利授权XX项。</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_monographs:        true
# resume_section_articles:        true
resume_section_patents:        true
#resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/godfanmiao/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://scholar.google.com/citations?user=aPlHReAAAAAJ&hl=zh-CN"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
